import { useState, useEffect, useRef } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Loader2, Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { SchemaDefinition } from "@/services/aiSchemaService";
import { Button } from "@/components/ui/button";
import { 
  generateCode, 
  CodeBundle, 
  TechStack
} from "@/services/aiCodeService";
import JSZip from "jszip";

// Create a static cache that persists even when component remounts
const globalCodeCache: Record<string, CodeBundle> = {};

interface CodePreviewProps {
  stack: TechStack | null;
  schema: SchemaDefinition | null;
  apiKey?: string;
  isCodeGenerated: boolean;
  onGenerateCode: () => void;
}

export function CodePreview({ stack, schema, apiKey, isCodeGenerated, onGenerateCode }: CodePreviewProps) {
  const [code, setCode] = useState<CodeBundle | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();
  const stackKey = stack ? `${stack.id}-${stack.language}-${stack.db}-${stack.framework}-${stack.orm}` : "";

  // Load from global cache on component mount or stack change
  useEffect(() => {
    if (stack && stackKey && globalCodeCache[stackKey]) {
      console.log("Loading code from global cache for stack:", stackKey);
      setCode(globalCodeCache[stackKey]);
    }
  }, [stack, stackKey]);

  // Create a function to handle generating/regenerating code
  const handleRegenerateCode = async () => {
    if (!stack || !schema) return;
    
    setIsGenerating(true);
    try {
      const generatedCode = await generateCode(schema, stack, apiKey);
      console.log("Generated code:", generatedCode);
      setCode(generatedCode);
      
      // Save to global cache
      globalCodeCache[stackKey] = generatedCode;
      
      // Notify parent that code has been generated
      onGenerateCode();
    } catch (error) {
      console.error("Error generating code:", error);
      toast({
        title: "Error",
        description: "Failed to generate code. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async () => {
    if (!code || !stack || !schema) {
      toast({
        title: "Error",
        description: "No code available to download.",
        variant: "destructive",
      });
      return;
    }

    try {
      const zip = new JSZip();
      
      // Add code files
      zip.file(`${stack.framework.toLowerCase()}-schema.js`, code.schema || '');
      zip.file(`${stack.framework.toLowerCase()}-model.js`, code.model || '');
      zip.file(`${stack.framework.toLowerCase()}-router.js`, code.router || '');
      
      // Add README.md with schema details
      const readme = generateReadme(schema, stack);
      zip.file("README.md", readme);

      // Generate and download the zip file
      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${stack.name.toLowerCase()}-${stack.db.toLowerCase()}-bundle.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      toast({
        title: "Download complete",
        description: "Your code bundle has been downloaded successfully.",
      });
    } catch (error) {
      console.error("Error downloading bundle:", error);
      toast({
        title: "Download failed",
        description: "Failed to download code bundle. Please try again.",
        variant: "destructive",
      });
    }
  };

  const generateReadme = (schema: SchemaDefinition, stack: TechStack): string => {
    let readme = `# ${stack.name} Project with ${stack.db}\n\n`;
    readme += `## Tech Stack\n\n`;
    readme += `- **Database**: ${stack.db}\n`;
    readme += `- **Language**: ${stack.language}\n`;
    readme += `- **Framework**: ${stack.framework}\n`;
    readme += `- **ORM**: ${stack.orm}\n\n`;
    
    readme += `## Schema Definition\n\n`;
    readme += `\`\`\`json\n${JSON.stringify(schema, null, 2)}\n\`\`\`\n\n`;
    
    readme += `## Generated Files\n\n`;
    readme += `- **Schema**: Database schema definition\n`;
    readme += `- **Model**: Data models implementation\n`;
    readme += `- **Router**: API routes implementation\n\n`;
    
    readme += `## Generated by SchemaCraft\n`;
    
    return readme;
  };

  // Determine if we have code already in the global cache
  const hasExistingCode = Boolean(stackKey && globalCodeCache[stackKey]);

  if (!stack) {
    return (
      <div className="flex h-full w-full items-center justify-center">
        <div className="text-center">
          <p className="text-muted-foreground">Select a tech stack to generate code</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-full flex-col overflow-hidden rounded-md border">
      <div className="border-b bg-muted/50 px-4 py-3">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-medium">{stack.name} Code</h3>
            <p className="text-xs text-muted-foreground">
              {stack.db} • {stack.language} • {stack.framework}
            </p>
          </div>
          <div className="flex space-x-2">
            <Button 
              onClick={handleRegenerateCode}
              disabled={isGenerating}
              size="sm"
              variant="outline"
            >
              {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : hasExistingCode ? "Regenerate" : "Generate Code"}
            </Button>
            <Button 
              onClick={handleDownload}
              disabled={isGenerating || !code}
              size="sm"
              className="bg-green-600 hover:bg-green-700"
            >
              <Download className="mr-2 h-4 w-4" />
              Download
            </Button>
          </div>
        </div>
      </div>
      
      <div className="flex-1 overflow-hidden p-4">
        {isGenerating ? (
          <div className="flex h-full flex-col items-center justify-center space-y-4">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">Generating code...</p>
          </div>
        ) : !code ? (
          <div className="flex h-full flex-col items-center justify-center space-y-4">
            <p className="text-sm text-muted-foreground">Click "Generate Code" to create your code bundle</p>
          </div>
        ) : (
          <Tabs defaultValue="schema" className="h-full">
            <TabsList className="mb-4">
              <TabsTrigger value="schema">Schema</TabsTrigger>
              <TabsTrigger value="model">Model</TabsTrigger>
              <TabsTrigger value="router">Router</TabsTrigger>
            </TabsList>
            <TabsContent value="schema" className="h-[calc(100%-40px)]">
              <pre className="h-full overflow-auto rounded-md bg-muted p-4 font-mono text-xs">
                <code>{code?.schema || "// No schema code generated yet"}</code>
              </pre>
            </TabsContent>
            <TabsContent value="model" className="h-[calc(100%-40px)]">
              <pre className="h-full overflow-auto rounded-md bg-muted p-4 font-mono text-xs">
                <code>{code?.model || "// No model code generated yet"}</code>
              </pre>
            </TabsContent>
            <TabsContent value="router" className="h-[calc(100%-40px)]">
              <pre className="h-full overflow-auto rounded-md bg-muted p-4 font-mono text-xs">
                <code>{code?.router || "// No router code generated yet"}</code>
              </pre>
            </TabsContent>
          </Tabs>
        )}
      </div>
    </div>
  );
}
